[tool.poetry]
name = "cenfind"
version = "0.16.1"
description = "Score cells for centrioles in IF data"
authors = ["Leo Burgy <leo.burgy@epfl.ch>"]
repository = "https://github.com/UPGON/cenfind"
readme = "README.md"
keywords = ["microscopy", "scientific", "biology", "image-analysis"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
attrs = "^22.2.0"
tifffile = "^2022.5.4"
numpy = ">=1.23.5,<2.0.0"
scipy = ">=1.9.3,<2.0.0"
opencv-python = "^4.7.0.72"
scikit-image = ">=0.20.0,<0.23.0"
scikit-learn = "^1.2.1"
stardist = ">=0.8.3,<0.10.0"
spotipy-detector = "^0.1.0"
ortools = ">=9.4.1874,<9.10.0"
csbdeep = ">=0.8.1,<0.9.0"
tensorflow = ">=2.13,<2.16"
tensorflow-metal = { version = ">=1.0.0,<2.0.0", markers = "sys_platform == 'darwin'" }
numba = ">=0.57.0,<0.60.0"
protobuf = ">=4.23.4,<5.0.0"
pandas = ">=1.5.3,<3.0.0"
tqdm = "^4.62.3"
albumentations = ">=1.3.0,<1.4.0"
seaborn = "^0.13.0"

[tool.poetry.scripts]
cenfind = "cenfind.__main__:main"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
python-dotenv = "^0.21.1"
pytomlpp = "^1.0.10"
labelbox = { extras = ["data"], version = "^3.46.0" }

[tool.poetry.group.docs.dependencies]
sphinx = "^7.3.7"
furo = "^2024.8.6"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "poetry.core.masonry.api"
