title = 'Foci detection'

author = 'Leo Burgy'
date = 2021-07-30

[dataset]
root = "/Volumes/work/datasets"

#RPE1wt_CEP63+CETN2+PCNT_1
#U2OS_CEP63+SAS6+PCNT_1
#RPE1wt_CEP152+GTU88+PCNT_1

name = "RPE1wt_CEP63+CETN2+PCNT_1"

[data]
channel = 2
position = [0, 0]

[structures.foci]
ks = 3
dist_foci = 2
factor = 3
blur = 'gaussian'

mask_radius = 3

[structures.nuclei]
threshold = 150

[options]
ANNOTATED = false
LEGEND = false
GROUND_TRUTH = true

ADD_FOCI = true
ADD_CENT = true
ADD_NUCLEI = true