name: Publish to Test PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  test_pypi_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install Poetry
        run: |
          export POETRY_HOME=/opt/poetry
          python3 -m venv $POETRY_HOME
          $POETRY_HOME/bin/pip install poetry==1.3.1
          $POETRY_HOME/bin/poetry --version
      - run: $POETRY_HOME/bin/poetry install
      - run: $POETRY_HOME/bin/poetry run pytest
      - run: $POETRY_HOME/bin/poetry config repositories.testpypi https://test.pypi.org/legacy/
      - run: $POETRY_HOME/bin/poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI }}
      - name: Publish package
        run: $POETRY_HOME/bin/poetry publish --build -r testpypi
